env:
  es6: true
extends:
  - standard
  - plugin:cypress/recommended
  - plugin:chai-friendly/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  "cypress/assertion-before-screenshot": "warn"
  "cypress/no-force": "warn"